# Generated by Django 5.2 on 2025-05-12 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='Material Name')),
            ],
        ),
        migrations.CreateModel(
            name='PumpMaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Maker Name')),
            ],
        ),
        migrations.CreateModel(
            name='PumpParts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_no', models.CharField(max_length=50, verbose_name='Part Number')),
                ('name', models.CharField(max_length=100, verbose_name='Part Name')),
                ('technical_details', models.FileField(blank=True, null=True, upload_to='technical_files', verbose_name='Technical Details')),
                ('drawing_file', models.FileField(blank=True, null=True, upload_to='drawings/', verbose_name='Drawing File')),
                ('cad_file', models.FileField(blank=True, null=True, upload_to='cad_files/', verbose_name='CAD File')),
                ('mapping', models.FileField(blank=True, null=True, upload_to='mapping_files/', verbose_name='Mapping File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('available', models.IntegerField(default=True, verbose_name='Available Quantity')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Spares.materials')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Spares.pumpparts')),
            ],
        ),
        migrations.CreateModel(
            name='PumpModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_models', to='Spares.pumpmaker')),
            ],
        ),
        migrations.CreateModel(
            name='PumpModelVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discharge_diameter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discharge Diameter (mm)')),
                ('stages', models.IntegerField(verbose_name='Number of Stages')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Spares.pumpmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spares.partmaterials')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_parts', to='Spares.pumpmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model', 'part_materials'), name='unique_model_part')],
            },
        ),
        migrations.CreateModel(
            name='ModelVariantPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_part_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spares.partmaterials')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_parts', to='Spares.pumpmodelvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variant', 'variant_part_materials'), name='unique_variant_part')],
            },
        ),
        migrations.AddConstraint(
            model_name='partmaterials',
            constraint=models.UniqueConstraint(fields=('part', 'materials'), name='unique_part_materials'),
        ),
    ]
