# Generated by Django 5.1.7 on 2025-04-19 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Maker Name")),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_no",
                    models.CharField(max_length=50, verbose_name="Part Number"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Part Name")),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Material"
                    ),
                ),
                (
                    "technical_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Technical Details"
                    ),
                ),
                (
                    "drawing_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="drawings/",
                        verbose_name="Drawing File",
                    ),
                ),
                (
                    "cad_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cad_files/",
                        verbose_name="CAD File",
                    ),
                ),
                (
                    "mapping",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="mapping_files/",
                        verbose_name="Mapping File",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PumpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Model Name")),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pump_models",
                        to="Spares.maker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discharge_diameter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Discharge Diameter (mm)",
                    ),
                ),
                ("stages", models.IntegerField(verbose_name="Number of Stages")),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="Spares.pumpmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelVariantPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_parts",
                        to="Spares.modelvariant",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Spares.part"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variant", "part"), name="unique_variant_part"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Spares.part"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_parts",
                        to="Spares.pumpmodel",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "part"), name="unique_model_part"
                    )
                ],
            },
        ),
    ]
