# Generated by Django 5.2 on 2025-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_Efficiency_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height1', models.FloatField(verbose_name='Height1')),
                ('height2', models.FloatField(verbose_name='Height2')),
                ('suction_pressure', models.FloatField(verbose_name='Suction Pressure')),
                ('discharge_pressure', models.FloatField(verbose_name='Discharge Pressure')),
                ('fluid_temperature', models.FloatField(verbose_name='Fluid Temperature')),
                ('nominal_flow_rate', models.FloatField(verbose_name='Qnp')),
                ('nominal_head', models.FloatField(verbose_name='Hnp')),
                ('pump_efficiency', models.FloatField(verbose_name='Pump Efficiency')),
                ('pump_speed', models.FloatField(verbose_name='Pump Speed N1')),
                ('motor_voltage', models.FloatField(verbose_name='Motor Voltage')),
                ('motor_current', models.FloatField(verbose_name='Motor Current')),
                ('motor_power_factor', models.FloatField(verbose_name='Motor Power Factor')),
                ('motor_power', models.FloatField(verbose_name='Power')),
                ('N2', models.FloatField(verbose_name='N2')),
                ('actual_flow_rate', models.FloatField(verbose_name='Actual Flow Rate')),
                ('pump_discharge_pressure', models.FloatField(verbose_name='Pump Discharge Pressure')),
                ('pump_suction_pressure', models.FloatField(verbose_name='Pump Suction Pressure')),
                ('text_curve_data', models.FileField(upload_to='test_curve_data/', verbose_name='Test Data')),
                ('actual_voltage', models.FloatField(verbose_name='Actual Voltage')),
                ('actual_current', models.FloatField(verbose_name='Actual Vlotage')),
                ('actual_power_factor', models.FloatField(verbose_name='Actual Power Factor')),
                ('actual_power', models.FloatField(verbose_name='Actual Power')),
                ('actual_efficiency', models.FloatField(verbose_name='Actual Efficiency')),
                ('no_hrs_pumprun', models.FloatField(verbose_name='No. of Hours Pump Run')),
                ('cost_of_electricity', models.FloatField(verbose_name='Cost of Electricity')),
            ],
            options={
                'verbose_name': 'Energy Efficiency Parameter',
                'verbose_name_plural': 'Energy Efficiency Parameters',
                'db_table': 'Energy_Efficiency_Parameters',
            },
        ),
    ]
