# Generated by Django 5.1.7 on 2025-04-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Energy_efficiency", "0002_alter_energy_efficiency_parameters_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energy_efficiency_parameters",
            name="is_draft",
        ),
    ]
